networks:
    default:
        name: cheese-app-network
        external: true
services:
    cheese-app-vector-db-cli:
        image: cheese-app-vector-db-cli
        container_name: cheese-app-vector-db-cli
        volumes:
            - ../../../secrets:/secrets
            - ../llm-rag:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: cheese-app-vector-db
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
